#
# This file contains configuration flags to customize your site
#

name: 抽筋的葡萄

description: A Front-End Develpoer

logo: logo.png
loading: loading.gif

#
# Flags below are optional
#

links:
  email: dy781745492@gmail.com
  facebook:
  github: dingyi1993
  instagram:
  linkedin:
  pinterest:
  rss: 666
  twitter: dingyi_1993
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  weibo: dingyi1993
  weixin: 666


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

google_analytics: UA-80833682-1
baidu_analytics: 666

url: http://www.choujindeputao.com

baseurl: ''

asset_path: /assets

paginate: 3
paginate_path: /blog/:num

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

version: v1.0.0_alpha

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

sass:
  style: :compressed

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
